var CurrentUserConstants = {
  CURRENT_USER_RECEIVED: "CURRENT_USER_RECEIVED",
  CURRENT_USER_ATTRIBUTE_RECEIVED: "CURRENT_USER_ATTRIBUTE_RECEIVED",
  CURRENT_USER_OWED_AMOUNT_RECEIVED: "CURRENT_USER_OWED_AMOUNT_RECEIVED",
  CURRENT_USER_LENDED_AMOUNT_RECEIVED: "CURRENT_USER_LENDED_AMOUNT_RECEIVED"
};

module.exports = CurrentUserConstants;
