var UserConstants = {
  USERS_RECEIVED: "USERS_RECEIVED",
  LENDED_AMOUNT_DATA_RECEIVED: "LENDED_AMOUNT_DATA_RECEIVED",
  OWED_AMOUNT_DATA_RECEIVED: "OWED_AMOUNT_DATA_RECEIVED"
};

module.exports = UserConstants;
